homeassistant:
  name: WCS Dev
  latitude: 45.5017
  longitude: -73.5673
  elevation: 30
  unit_system: metric
  time_zone: America/Toronto
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 172.16.0.0/12
      trusted_users:
        127.0.0.1: 31c1f8d9a68b4f4090f8193b7db0a3e0
      allow_bypass_login: true
    - type: homeassistant

default_config:

logger:
  default: info
  logs:
    custom_components.waste_collection_schedule: debug

# Change these config to your needs
waste_collection_schedule:
  sources:
    - name: muellmax_de
      args:
        service: Rsa
        mm_frm_ort_sel: Alfter
        mm_frm_str_sel: Ahrweg (105-Ende/94-Ende)

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
#debugpy:
